-- ============================================================================
-- Move trip creation into a SECURITY DEFINER function.
-- The multi-step client flow (insert trip + returning + insert members) was
-- racing with RLS/RETURNING checks; consolidating into one server-side
-- transaction fixes it and keeps everything atomic.
-- ============================================================================

create or replace function public.create_trip(
  trip_name text,
  trip_base_currency text default 'EUR',
  friend_names text[] default '{}'::text[]
)
returns table (
  id uuid,
  name text,
  base_currency text,
  code text,
  owner_id uuid,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  new_trip_id uuid;
  user_name text;
  user_color text;
  friend_name text;
  avatar_colors text[] := array[
    '#DA9AC7', '#8DCDE2', '#A7D296', '#E9A6A7',
    '#EEEDB3', '#E5D8BD', '#85D1BD', '#96B0FD'
  ];
  friend_idx int := 0;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;
  if trip_name is null or trim(trip_name) = '' then
    raise exception 'Trip name is required';
  end if;

  -- Fetch caller's profile for the owner-member row.
  select p.name, p.color into user_name, user_color
  from profiles p where p.id = auth.uid();
  if user_name is null or user_name = '' then user_name := 'You'; end if;
  if user_color is null then user_color := '#CBA5FD'; end if;

  -- Create the trip (code auto-generated by the column default).
  insert into trips (name, base_currency, owner_id)
  values (trim(trip_name), coalesce(trip_base_currency, 'EUR'), auth.uid())
  returning trips.id into new_trip_id;

  -- Owner is the first member.
  insert into trip_members (trip_id, user_id, name, color)
  values (new_trip_id, auth.uid(), user_name, user_color);

  -- Placeholder members (user_id null, can be claimed later via code).
  if friend_names is not null then
    foreach friend_name in array friend_names loop
      if length(trim(friend_name)) > 0 then
        insert into trip_members (trip_id, user_id, name, color)
        values (
          new_trip_id,
          null,
          trim(friend_name),
          avatar_colors[(friend_idx % array_length(avatar_colors, 1)) + 1]
        );
        friend_idx := friend_idx + 1;
      end if;
    end loop;
  end if;

  return query
    select t.id, t.name, t.base_currency, t.code, t.owner_id, t.created_at
    from trips t where t.id = new_trip_id;
end;
$$;

grant execute on function public.create_trip(text, text, text[]) to authenticated;

-- Also broaden the trips SELECT policy so the owner can always read their
-- own trips (defense in depth: even if they briefly aren't in trip_members).
drop policy if exists "trips: members read" on trips;
create policy "trips: members read"
  on trips for select
  using (owner_id = auth.uid() or public.is_trip_member(id));
